//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.02 at 10:21:37 AM IST 
//


package org.lucksoft.airlineaggregator.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Specifies the aircraft equipment type.
 * 
 * <p>Java class for EquipmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EquipmentType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.opentravel.org/OTA/2003/05&gt;StringLength0to64"&gt;
 *       &lt;attribute name="AirEquipType" use="required" type="{http://www.opentravel.org/OTA/2003/05}StringLength3" /&gt;
 *       &lt;attribute name="ChangeofGauge" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EquipmentType", propOrder = {
    "value"
})
@XmlSeeAlso({
    EquipmentTypePref.class
})
public class EquipmentType
    implements Cloneable, CopyTo, Equals, HashCode, ToString
{

    @XmlValue
    protected String value;
    @XmlAttribute(name = "AirEquipType", required = true)
    protected String airEquipType;
    @XmlAttribute(name = "ChangeofGauge")
    protected Boolean changeofGauge;

    /**
     * Used for Character Strings, length 0 to 64
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the airEquipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirEquipType() {
        return airEquipType;
    }

    /**
     * Sets the value of the airEquipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirEquipType(String value) {
        this.airEquipType = value;
    }

    /**
     * Gets the value of the changeofGauge property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isChangeofGauge() {
        if (changeofGauge == null) {
            return false;
        } else {
            return changeofGauge;
        }
    }

    /**
     * Sets the value of the changeofGauge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChangeofGauge(Boolean value) {
        this.changeofGauge = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theValue;
            theValue = this.getValue();
            strategy.appendField(locator, this, "value", buffer, theValue);
        }
        {
            String theAirEquipType;
            theAirEquipType = this.getAirEquipType();
            strategy.appendField(locator, this, "airEquipType", buffer, theAirEquipType);
        }
        {
            boolean theChangeofGauge;
            theChangeofGauge = ((this.changeofGauge!= null)?this.isChangeofGauge():false);
            strategy.appendField(locator, this, "changeofGauge", buffer, theChangeofGauge);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof EquipmentType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EquipmentType that = ((EquipmentType) object);
        {
            String lhsValue;
            lhsValue = this.getValue();
            String rhsValue;
            rhsValue = that.getValue();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "value", lhsValue), LocatorUtils.property(thatLocator, "value", rhsValue), lhsValue, rhsValue)) {
                return false;
            }
        }
        {
            String lhsAirEquipType;
            lhsAirEquipType = this.getAirEquipType();
            String rhsAirEquipType;
            rhsAirEquipType = that.getAirEquipType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "airEquipType", lhsAirEquipType), LocatorUtils.property(thatLocator, "airEquipType", rhsAirEquipType), lhsAirEquipType, rhsAirEquipType)) {
                return false;
            }
        }
        {
            boolean lhsChangeofGauge;
            lhsChangeofGauge = ((this.changeofGauge!= null)?this.isChangeofGauge():false);
            boolean rhsChangeofGauge;
            rhsChangeofGauge = ((that.changeofGauge!= null)?that.isChangeofGauge():false);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "changeofGauge", lhsChangeofGauge), LocatorUtils.property(thatLocator, "changeofGauge", rhsChangeofGauge), lhsChangeofGauge, rhsChangeofGauge)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theValue;
            theValue = this.getValue();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "value", theValue), currentHashCode, theValue);
        }
        {
            String theAirEquipType;
            theAirEquipType = this.getAirEquipType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "airEquipType", theAirEquipType), currentHashCode, theAirEquipType);
        }
        {
            boolean theChangeofGauge;
            theChangeofGauge = ((this.changeofGauge!= null)?this.isChangeofGauge():false);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "changeofGauge", theChangeofGauge), currentHashCode, theChangeofGauge);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof EquipmentType) {
            final EquipmentType copy = ((EquipmentType) draftCopy);
            if (this.value!= null) {
                String sourceValue;
                sourceValue = this.getValue();
                String copyValue = ((String) strategy.copy(LocatorUtils.property(locator, "value", sourceValue), sourceValue));
                copy.setValue(copyValue);
            } else {
                copy.value = null;
            }
            if (this.airEquipType!= null) {
                String sourceAirEquipType;
                sourceAirEquipType = this.getAirEquipType();
                String copyAirEquipType = ((String) strategy.copy(LocatorUtils.property(locator, "airEquipType", sourceAirEquipType), sourceAirEquipType));
                copy.setAirEquipType(copyAirEquipType);
            } else {
                copy.airEquipType = null;
            }
            if (this.changeofGauge!= null) {
                boolean sourceChangeofGauge;
                sourceChangeofGauge = ((this.changeofGauge!= null)?this.isChangeofGauge():false);
                boolean copyChangeofGauge = strategy.copy(LocatorUtils.property(locator, "changeofGauge", sourceChangeofGauge), sourceChangeofGauge);
                copy.setChangeofGauge(copyChangeofGauge);
            } else {
                copy.changeofGauge = null;
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new EquipmentType();
    }

}
